# Generated by Django 3.2.12 on 2022-03-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_auto_20220324_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notification'},
        ),
    ]
