# Generated by Django 4.0.8 on 2023-02-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, default='avatar/default.png', help_text='个人资料图片', max_length=1024, null=True, verbose_name='头像'),
        ),
    ]
