# Generated by Django 4.0.8 on 2023-02-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_rename_src_upload_file'),
        ('users', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_departments',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_departments',
            field=models.ManyToManyField(blank=True, help_text='The Departments this user belongs to. A user will get all permissions granted to each of their Departments.', null=True, related_name='user_departments', related_query_name='user', to='system.department', verbose_name='Departments'),
        ),
    ]
