# Generated by Django 4.0.8 on 2023-02-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_role_alias'),
        ('users', '0007_remove_userprofile_user_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_departments',
            field=models.ManyToManyField(blank=True, help_text='The Departments this user belongs to. A user will get all permissions granted to each of their Departments.', null=True, related_name='user_departments', related_query_name='user', to='system.department', verbose_name='科室'),
        ),
    ]
