# Generated by Django 4.0.8 on 2023-02-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_role_competences_alter_role_menus'),
        ('users', '0008_alter_userprofile_user_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_departments',
            field=models.ManyToManyField(help_text='The Departments this user belongs to. A user will get all permissions granted to each of their Departments.', related_name='user_departments', related_query_name='user', to='system.department', verbose_name='科室'),
        ),
    ]
