# Generated by Django 4.0.8 on 2023-02-03 07:42

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='状态说明字段', verbose_name='激活状态')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('label', models.CharField(blank=True, help_text='机柜编号:微模块1-1-2,微模块2-1-2等', max_length=255, unique=True, verbose_name='机柜编号')),
                ('units', models.IntegerField(blank=True, help_text='单元数量:20,25等', unique=True, verbose_name='单元数量')),
                ('remark', models.TextField(help_text='备注:微模块1等', null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '机柜',
                'verbose_name_plural': '机柜',
            },
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='状态说明字段', verbose_name='激活状态')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('label', models.CharField(blank=True, help_text='数据中心名称:老院机房,新院机房等', max_length=255, unique=True, verbose_name='数据中心名称')),
            ],
            options={
                'verbose_name': '数据中心',
                'verbose_name_plural': '数据中心',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='状态说明字段', verbose_name='激活状态')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('label', models.CharField(help_text='设备类型名:核心交换机等', max_length=255, unique=True, verbose_name='设备名称')),
                ('model_spec', models.CharField(blank=True, help_text='型号规格:ar2000等', max_length=255, null=True, verbose_name='型号规格')),
                ('manufacturer', models.CharField(blank=True, help_text='生产厂家:华三，华为等', max_length=255, null=True, verbose_name='生产厂家')),
                ('warranty_period', models.DateField(blank=True, help_text='生产厂家:2021/11/22等', null=True, verbose_name='保修期限')),
                ('space', models.IntegerField(blank=True, help_text='空间占用：占用的机柜单元数量,2,3等', unique=True, verbose_name='空间占用')),
                ('location', models.CharField(help_text='备注使用位置:楼层，办公室等', max_length=255, null=True, verbose_name='使用位置')),
                ('bind_Cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_Cabinet', to='itam.cabinet', verbose_name='绑定机柜')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='状态说明字段', verbose_name='激活状态')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('label', models.CharField(blank=True, help_text='设备类型名:PC,路由器,交换机等', max_length=255, unique=True, verbose_name='设备类型名')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='状态说明字段', verbose_name='激活状态')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('ip_address', models.GenericIPAddressField(help_text='需要管理的IP地址信息', unique=True, verbose_name='IP地址')),
                ('location', models.CharField(help_text='备注使用位置:楼层，办公室等', max_length=255, null=True, verbose_name='使用位置')),
                ('purpose', models.TextField(help_text='备注IP地址使用情况', null=True, verbose_name='用途备注')),
                ('bind_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_bind_device', to='itam.device', verbose_name='绑定设备')),
                ('use_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_use_device', to='itam.device', verbose_name='使用设备')),
            ],
            options={
                'verbose_name': 'IP地址',
                'verbose_name_plural': 'IP地址',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_type', to='itam.devicetype', verbose_name='设备类型'),
        ),
    ]
