# Generated by Django 4.0.8 on 2023-02-07 06:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ipaddress',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
