# Generated by Django 4.0.8 on 2023-02-07 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0002_alter_ipaddress_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ipaddress',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='data_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_of_dc', to='itam.datacenter', verbose_name='数据中心'),
        ),
    ]
