# Generated by Django 4.0.8 on 2023-02-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0003_alter_ipaddress_managers_cabinet_data_center'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AlterField(
            model_name='device',
            name='space',
            field=models.IntegerField(blank=True, help_text='空间占用：占用的机柜单元数量,2,3等', verbose_name='空间占用'),
        ),
    ]
