# Generated by Django 4.0.8 on 2023-02-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0005_alter_device_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='usage_status',
            field=models.IntegerField(choices=[(1, '空闲中'), (2, '占用中'), (3, '被使用'), (9, '其他')], default=1, help_text='备注IP地址状态情况', verbose_name='使用状态'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='location',
            field=models.CharField(blank=True, help_text='备注使用位置:楼层，办公室等', max_length=255, null=True, verbose_name='使用位置'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='purpose',
            field=models.TextField(blank=True, help_text='备注IP地址使用情况', null=True, verbose_name='用途备注'),
        ),
    ]
