# Generated by Django 4.0.8 on 2023-02-13 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itam', '0007_alter_ipaddress_options_ipaddress_os_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='usage_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_bind_user', to=settings.AUTH_USER_MODEL, verbose_name='占用人'),
        ),
    ]
