# Generated by Django 4.0.8 on 2023-02-07 06:37

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': '系统配置', 'verbose_name_plural': '系统配置'},
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(default='avatar/default.png', help_text='存放文件字段', upload_to=common.utils.PathAndRename('avatar/2023-02-07/'), verbose_name='上传的文件'),
        ),
    ]
