# Generated by Django 4.0.8 on 2023-02-18 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_upload_alter_uploadfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='src',
            new_name='file',
        ),
    ]
