# Generated by Django 4.0.8 on 2023-02-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_role_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='sort',
            field=models.IntegerField(default=0, help_text='排序', verbose_name='排序'),
        ),
    ]
