# Generated by Django 4.0.8 on 2023-02-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_role_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='competences',
            field=models.ManyToManyField(related_name='role_competences', related_query_name='role', to='system.competence', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(related_name='role_menus', related_query_name='role', to='system.menu', verbose_name='菜单'),
        ),
    ]
