# Generated by Django 4.0.8 on 2023-02-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_competence_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sort',
            field=models.IntegerField(default=0, help_text='排序', verbose_name='排序'),
        ),
    ]
