# Generated by Django 4.0.8 on 2023-02-24 06:33

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_department_options_alter_upload_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='belongs_system',
            field=models.CharField(choices=[('whitenoise.runserver_nostatic', 'Runserver_Nostatic'), ('jazzmin', 'Jazzmin'), ('django.contrib.auth', 'Authentication and Authorization'), ('django.contrib.contenttypes', 'Content Types'), ('django.contrib.sessions', 'Sessions'), ('django.contrib.sites', 'Sites'), ('django.contrib.messages', 'Messages'), ('django.contrib.staticfiles', 'Static Files'), ('django.contrib.admin', 'Administration'), ('django.forms', 'Forms'), ('crispy_forms', 'Crispy_Forms'), ('crispy_bootstrap5', 'Crispy_Bootstrap5'), ('allauth', 'Allauth'), ('allauth.account', 'Accounts'), ('allauth.socialaccount', 'Social Accounts'), ('django_celery_beat', 'Periodic Tasks'), ('rest_framework', 'Django REST framework'), ('rest_framework_sso', 'Rest_Framework_Sso'), ('rest_framework.authtoken', 'Auth Token'), ('rest_framework_filters', 'Rest_Framework_Filters'), ('corsheaders', 'django-cors-headers'), ('drf_spectacular', 'drf-spectacular'), ('notifications', '通知'), ('notifications_rest', 'Notifications_Rest'), ('mptt', 'mptt'), ('explorer', 'SQL Explorer'), ('users', '用户管理'), ('system', '系统管理'), ('itam', '资产管理'), ('drgs', '单病种监测'), ('compressor', 'Compressor'), ('debug_toolbar', 'Debug Toolbar'), ('django_extensions', 'Django Extensions')], default='system', help_text='所属子系统系统：system,drgs', max_length=100, verbose_name='所属系统'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.ImageField(blank=True, default='avatar/default.png', help_text='上传文件', null=True, upload_to=common.utils.PathAndRename('upload/2023-02-24/'), verbose_name='上传文件'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(default='avatar/default.png', help_text='存放文件字段', upload_to=common.utils.PathAndRename('avatar/2023-02-24/'), verbose_name='上传的文件'),
        ),
    ]
