# Generated by Django 4.0.8 on 2023-02-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_menu_belongs_system_alter_upload_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='belongs_system',
            new_name='sub_system',
        ),
    ]
