# Generated by Django 4.0.8 on 2023-02-22 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staresults',
            options={'ordering': ['cls'], 'verbose_name': '统计结果', 'verbose_name_plural': '统计结果'},
        ),
    ]
