# Generated by Django 4.0.8 on 2023-02-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drgs', '0003_remove_staresults_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singledisease',
            name='remark',
            field=models.TextField(blank=True, help_text='备注:微模块1等', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='singledisease',
            name='second_diagnostic_code',
            field=models.CharField(blank=True, help_text='第二诊断 ICD-10 编码：I21.0 至 I21.3 的出院患者', max_length=2048, null=True, verbose_name='第二诊断编码'),
        ),
    ]
