# Generated by Django 4.0.8 on 2023-02-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drgs', '0004_alter_singledisease_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singledisease',
            name='special_requirements',
            field=models.CharField(blank=True, default=None, help_text='特殊诊断要求：或 I42 至 I43 伴第二诊断为 I50的出院患者', max_length=2048, null=True, verbose_name='特殊诊断要求'),
        ),
    ]
