# Generated by Django 4.0.8 on 2023-02-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drgs', '0006_remove_singledisease_special_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singledisease',
            name='is_adult',
            field=models.BooleanField(default=False, help_text='是否特殊年龄：True：是，False：否', verbose_name='是否特殊年龄'),
        ),
    ]
