# Generated by Django 4.0.8 on 2023-02-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drgs', '0007_alter_singledisease_is_adult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singledisease',
            old_name='special_diagnostic_code',
            new_name='special_second_diagnostic',
        ),
    ]
