# Generated by Django 4.0.8 on 2023-02-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drgs', '0008_rename_special_diagnostic_code_singledisease_special_second_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singledisease',
            name='max_age',
            field=models.IntegerField(default=0, help_text='最大年龄:0,0为不限制最大年龄', verbose_name='最大年龄'),
        ),
    ]
