# Generated by Django 4.0.8 on 2023-02-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drgs', '0010_alter_singledisease_options_singledisease_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singledisease',
            options={'ordering': ['sort'], 'verbose_name': '单病种指标', 'verbose_name_plural': '单病种指标'},
        ),
        migrations.RenameField(
            model_name='singledisease',
            old_name='parent',
            new_name='parentId',
        ),
    ]
